### ISSUE TITLE
let vs. const

### ISSUE THREAD

**Issue by thujone** [bibiqiqi/Eat_The_Weeds#1]
https://github.com/bibiqiqi/Eat_The_Weeds/blob/1e1524e4081aae1c29703314de03fd093cba18e2/app.js#L3

The idea with `let` and `const` is that you should use `const` whenever possible, and I believe all these could be `const` instead of `let`. Strings and numbers cannot be reassigned to a variable with `const`, but arrays and objects use variable names as references, not values. If you're not clear on this, you might want to read up on the keywords.

**Comment by bibiqiqi** [comment]
i initially set these as const, but my linter gave me an error message, because they're being initialized to undefined, so once they're defined, i'm attempting to override the initial definition
